### ISSUE TITLE
网页现在打开这个音乐界面 显示的封面 太大了 错位了

### ISSUE THREAD

**Issue by yiyinyiyang** [bigfa/nm#16]
网页现在打开这个音乐界面 显示的封面 太大了 错位了

**Comment by bigfa** [comment]
大概率是你自己主题的问题，可以切换默认主题进行测试下。

**Comment by yiyinyiyang** [comment]
是你自己的那个主页上面的音乐界面  你自己看看https://coffin.wpista.com/music

**Comment by yiyinyiyang** [comment]
是你自己的页面：https://coffin.wpista.com/music 这个页面 在opera 和 ie 上面浏览是正确的 在Chrome上面是错位的 我以前用的是DUX显示正确的 现在错位了 音乐封面变的很大

**Comment by yiyinyiyang** [comment]
这是在Chrome浏览器下面的 截图
![错位](https://user-images.githubusercontent.com/55334719/67160706-30b75800-f386-11e9-9042-82b848a1223c.png)

**Comment by yiyinyiyang** [comment]
我是在这三个浏览器 查看MUSIC 页面都是错位的
