### ISSUE TITLE
直接插入歌曲网址不显示歌曲

### ISSUE THREAD

**Issue by vra** [bigfa/nm#3]
您好，感谢您制作的这个很棒的插件。
我在使用插件的时候，启用插件后，直接在文章中插入歌曲地址，打开文章的时候，显示的是空白，您知道是什么原因吗？
如果只要在文章中插入歌曲，是不需要设置音乐页面地址的吧？

**Comment by bigfa** [comment]
你可以打开wp_debug查看哪来报错

**Comment by vra** [comment]
你好，感谢回复。我在wp-config.php中打开DEBUG开关后，在网页上显示的错误是`Call to undefined function curl_init()`，我查了下是因为我的系统没有装`pip5-curl`这个包，通过apt-get安装后就歌曲就可以正常播放了。
感谢你的帮助~
